name: twod
description: TBD
version: 0.0.0
homepage: https://github.com/matanlurey/twod

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  js: ^0.6.4
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.2.0
  build_test: ^2.1.5
  build_web_compilers: ^3.2.5
  coverage: ^1.5.0
  neodart: ^0.1.1
  test: ^1.21.4
